import kubectls drain implementation
flatcar-linux/flatcar-linux-update-operator pull request #152
Opened 2022-04-11 12:35 UTC by jakekeeys

# Import and consume Kubectl drain implementation

Fixes https://github.com/flatcar-linux/flatcar-linux-update-operator/issues/16

This brings in the drain implementation from kubectl behind a new feature flag `use-kubectl-drain`.

When enabled this replaces the local find and delete pods implementation with kubectls find and delete/evict.

Where evictions are supported by the cluster they will be used over the traditional delete and thus pod disruption polices will honoured

## How to use

start the agent with the feature flag

```
command:
    - "/bin/update-agent"
    - -use-kubectl-drain=true
```

annotate a node to trigger a reboot

```
kubectl annotate node <node-name> --overwrite flatcar-linux-update.v1.flatcar-linux.net/reboot-needed="true"
```

profit

```
flatcar-linux-update-operator-6659648fc6-4gmfb update-operator I0411 12:14:14.260423       1 operator.go:513] Found 1 nodes that need a reboot
flatcar-linux-update-operator-6659648fc6-4gmfb update-operator I0411 12:15:46.505060       1 operator.go:571] Found 0 rebooted nodes
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.378080       1 agent.go:292] draining node using kubectl drain implementation
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545224       1 main.go:108] evicting pod kube-system/calico-typha-66bb9dfbb4-5q7hd
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545250       1 main.go:108] evicting pod sys-vault/terraform-applier-0
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545280       1 main.go:108] evicting pod kube-system/cert-manager-6f96c5b8fd-fm5kc
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545304       1 main.go:108] evicting pod sys-minio/minio-nas-gw-7956b6f56-gx7bf
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545253       1 main.go:108] evicting pod kube-system/k8s-sidecar-injector-5b76cd9c44-scc87
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545366       1 main.go:108] evicting pod sys-mon/grafana-7b45495646-6k8kw
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545422       1 main.go:108] evicting pod sys-mon/thanos-query-shared-56568c9c48-7vbbq
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545464       1 main.go:108] evicting pod kube-system/metrics-server-5f84785dcc-zlx7w
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545501       1 main.go:108] evicting pod sys-prom/thanos-query-658857686-g5tzp
flatcar-linux-update-agent-dqbmf update-agent I0411 12:15:47.545575       1 main.go:108] evicting pod kube-system/cert-manager-webhook-56db8c9bfc-jldrl
```

2022-04-11 16:22 UTC, invidian commented
Hey @jakekeeys, thanks for opening the PR. I will try to review it tomorrow.

2022-04-12 09:57 UTC, invidian requested changes
Hey @jakekeeys, thanks for opening the PR! I left some comments which I believe should be addressed before we merge.

2022-04-12 09:57 UTC, invidian commented on cmd/update-agent/main.go
> +type KlogOutWriter struct{}
This 2 types does not need to be exported.

2022-04-12 09:57 UTC, invidian commented on cmd/update-agent/main.go
> +	useKubectlDrain = flag.Bool("use-kubectl-drain", false, "Use kubectl drain implementation to drain nodes")
With which k8s version `k8s.io/kubectl/pkg/drain` is compatible with? If it's enough versions, we can just change the implementation of agent, there is no need to make this opt-in I think.

2022-04-12 09:57 UTC, invidian commented on cmd/update-agent/main.go
> +		Ctx:                 nil,
If we construct this object in agent, we will have access to context as well.

2022-04-12 09:57 UTC, invidian commented on examples/deploy/rbac/cluster-role.yaml
> +      - create
I think we should have a separate rule to allow creating eviction, there is no need to allow creating pods.

2022-04-12 09:57 UTC, invidian commented on go.mod
> +	k8s.io/api v0.23.5
Can we omit updating the dependencies? It's better to do it separately.

2022-04-12 09:57 UTC, invidian commented on pkg/agent/agent.go
> +		deletion, errs := k.dh.GetPodsForDeletion(k.nodeName)
This is not tested and it actually violates the existing spec, as it will attempt to delete pods in `kube-system` namespace.

2022-04-12 11:09 UTC, jakekeeys commented on cmd/update-agent/main.go
> +	useKubectlDrain = flag.Bool("use-kubectl-drain", false, "Use kubectl drain implementation to drain nodes")
1.5 according to the docs https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#before-you-begin
the code we're re using here also uses the discovery api to determine if evictions are supported and will fall back to deletion if not

2022-04-12 11:11 UTC, invidian commented on cmd/update-agent/main.go
> +	useKubectlDrain = flag.Bool("use-kubectl-drain", false, "Use kubectl drain implementation to drain nodes")
Thanks for checking. Let's just use this drainer in the agent implementation and drop the old one.

2022-04-12 11:23 UTC, jakekeeys commented on pkg/agent/agent.go
> +		deletion, errs := k.dh.GetPodsForDeletion(k.nodeName)
yeah i wanted to bring this up, i can re introduce the same label filters but we're about to reboot the node at which point those `kube-system` containers are going to be culled anyway and probably in a less graceful manner. what was the thinking behind filtering them out?

2022-04-12 11:28 UTC, invidian commented on pkg/agent/agent.go
> +		deletion, errs := k.dh.GetPodsForDeletion(k.nodeName)
Existing code comment says:
```
  // XXX: Ignoring kube-system is a simple way to avoid eviciting
  // critical components such as kube-scheduler and
  // kube-controller-manager.
```

This might be a legacy thing, with bootkube, the pod checkpointer would remove the pod checkpoints together with regular pods, so the cluster wouldn't recover in case of rebooting a single controller node.

I think we should keep this intact to avoid disruption for now.

In the future, we should probably make this configurable for agent, with existing default, to give people an option to delete all pods when it's safe. And maybe at some point we can consider changing the default.

2022-04-12 11:51 UTC, jakekeeys commented on go.mod
> +	k8s.io/api v0.23.5
done

2022-04-12 11:52 UTC, jakekeeys commented on examples/deploy/rbac/cluster-role.yaml
> +      - create
done

2022-04-12 11:52 UTC, jakekeeys commented on cmd/update-agent/main.go
> +		Ctx:                 nil,
done

2022-04-12 11:52 UTC, jakekeeys commented on cmd/update-agent/main.go
> +	useKubectlDrain = flag.Bool("use-kubectl-drain", false, "Use kubectl drain implementation to drain nodes")
done

2022-04-12 12:46 UTC, invidian requested changes
Some more feedback/suggestions. Also please rebase the PR on latest master, I've added some missing linting #153, which should catch some styling inconsistencies introduced with this PR which should be fixed.

Please let me know if there is anything not clear I should further explain or you disagree with, I'm happy to discuss.

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +}
Perhaps we can have a single type with `func(args ...interface{})` as an anonymous field, so we have single `Write` function and we can initialize it as `&klogWriter{klog.Info}` and `&klogWriter{klog.Error}`.

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +		Ctx:                 ctx,
We should be also specifying `Timeout: k.reapTimeout` here perhaps? Or should this value be used in `GracePeriodSeconds`?

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +	toDelete := k8sutil.FilterPods(pods.Pods(), func(p *corev1.Pod) bool {
Instead of using this, we should be able to use `AdditionalFilters` in drainer configuration I guess?

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +	UseKubectlDrain         bool
This fields are no longer needed I think.

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +	dh                      *drain.Helper
Instead of depending on specific type `*drain.Helper`, I suggest we create unexported interface e.g.:
```go
type drainer interface {
  GetPodsForDeletion(nodeName string) (*drain.PodDeleteList, []error)
  DeleteOrEvictPods(pods corev1Pod, error)
}
```

This way, we explicitly state what parts of the Helper we use (or what would alternative implementation have to implement) and reduces the possible inherited complexity (as we only get access to two methods, instead of all possible methods helper implement).

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +		clientset:               config.Clientset,
With this, I think `pg` and `dsg` fields will no longer be used so they can be removed.

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +		Client:              k.clientset,
Bummer that helper takes entire clientset as a dependency, so we have to carry on with it.

(just a comment, no action needed)

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +	"k8s.io/kubectl/pkg/drain"
Imports are not properly sorted. CI should catch that (I approved it's runs).

2022-04-12 12:46 UTC, invidian commented on pkg/agent/agent.go
> +	if err != nil {
Shorter notation should be preferred.
```suggestion
	if err := dh.DeleteOrEvictPods(toDelete); err != nil {
```

2022-04-12 12:52 UTC, invidian reviewed
Last thing, agent package has right now almost 100% test coverage, except I think 3 statements which are not reachable and will be removed soon. I'd like to have test coverage for new implementation as well. I think the existing property/behavior tests will remain as it is and error handling errors might require change/removal, as we may not only fail on:
- getting pods for deletion
- deleting pods

The following error cases will be handled by the helper now:
- timing out waiting for pods eviction
- getting pods while waiting for deletion

2022-04-13 10:43 UTC, jakekeeys commented on pkg/agent/agent.go
> +}
done

2022-04-13 10:59 UTC, jakekeeys commented on pkg/agent/agent.go
> +		Ctx:                 ctx,
`Timeout` isn't documented but looks to be a global timeout for the drain itself, when reached it will return an error
`GracePeriodSeconds` is documented as follows
```	
// GracePeriodSeconds is how long to wait for a pod to terminate.
// IMPORTANT: 0 means "delete immediately"; set to a negative value
// to use the pod's terminationGracePeriodSeconds.
```
`reapTimeout` was implemented as a per pod delete timeout at which point the wait/poll func would return (not sure with with an error or not) but in either scenario log the pod name and return

GracePeriodSeconds is probably closest in terms of behaviour but i'd like to change the default value of `reapTimeout` to -1 which will cause it to base the per pod termination timeouts based on the pods `TerminationGracePeriod` if configured, or the kubernetes default of 30s

2022-04-13 11:17 UTC, jakekeeys commented on pkg/agent/agent.go
> +	toDelete := k8sutil.FilterPods(pods.Pods(), func(p *corev1.Pod) bool {
done

2022-04-13 11:18 UTC, jakekeeys commented on pkg/agent/agent.go
> +	UseKubectlDrain         bool
done

2022-04-13 11:18 UTC, jakekeeys commented on pkg/agent/agent.go
> +		clientset:               config.Clientset,
done

2022-04-13 11:19 UTC, jakekeeys commented on pkg/agent/agent.go
> +	"k8s.io/kubectl/pkg/drain"
done

2022-04-13 11:20 UTC, jakekeeys commented on pkg/agent/agent.go
> +	if err != nil {
done

2022-04-13 11:40 UTC, jakekeeys commented on pkg/agent/agent.go
> +	dh                      *drain.Helper
done

2022-04-13 11:50 UTC, invidian commented on pkg/agent/agent.go
> +		Ctx:                 ctx,
Hmm, so in existing implementation, we wait `reapTimeout` per pod, while drain helper has a global timeout for all pods, so the window will be slightly smaller I guess, though I suppose it should still be acceptable.

Given that we ignore all errors from deleting pods anyway and we only log them, I think it should be fine to set the `Timeout` field to `reapTimout`. And `reapTimeout` is also user configurable, so if there is a regression in waiting time, user can still increase it if needed.

Maybe I'll open an issue to implement some smarter way to respect `TerminationGracePeriod`.

2022-04-21 18:55 UTC, invidian commented on pkg/agent/agent.go
> +		Ctx:                 ctx,
Thank you! I'll review the PR early next week.

2022-04-22 07:17 UTC, jepio commented
@jakekeeys:
@invidian is out until the 25th

2022-04-26 20:46 UTC, invidian requested changes
Thanks again on the work on this PR @jakekeeys. I really appreciate it.

There are mainly some styling changes remaining, to keep code more maintainable and one about the tests, which I think needs to be changed. See the comments for more details.

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +			t.Errorf("unknown version %s", version)
This should be `Fatalf`, as otherwise we try to remove "" pod in "" namespace.

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +				t.Errorf("failed to delete pod: %s/%s", namespace, name)
```suggestion
				t.Errorf("Failed to delete pod %s/%s: %v", namespace, name, err)
```

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +			if err != nil {
```suggestion
			if err := clientset.CoreV1().Pods(namespace).Delete(ctx, name, metav1.DeleteOptions{}); err != nil {
```

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +func addEvictionSupport(t *testing.T, clientset *fake.Clientset, version string) {
```suggestion
func addEvictionSupport(ctx context.Context, t *testing.T, clientset *fake.Clientset) {
```

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +		Version: version,
```suggestion
		Version: "v1",
```

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +			t.Errorf("unknown version %s", version)
This whole thing can be simplified when we drop another version support.

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +			err := clientset.CoreV1().Pods(namespace).Delete(context.TODO(), name, metav1.DeleteOptions{})
Do we need to run it in a goroutine? I think it should be fine to drop this code as well.

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +				return true, nil, nil
So IIUC, this will make eviction calls not return error, but it won't remove the pods either, which will make `DeleteOrEvictPods` block until the timeout, correct? Perhaps we can add a comment for this as this doesn't seem so obvious.

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +				})
This whole code should be refactored with the function above, so we don't duplicate so much test setup code (which is already too large).

For example:
```diff
diff --git a/pkg/agent/agent_test.go b/pkg/agent/agent_test.go
index 65d6ccc0..1fcfe852 100644
--- a/pkg/agent/agent_test.go
+++ b/pkg/agent/agent_test.go
@@ -782,16 +782,11 @@ func Test_Running_agent(t *testing.T) {

                        allExpectedPodsScheduledForRemoval := make(chan struct{}, 2)

-                       fakeClient.PrependReactor("delete", "pods", func(action k8stesting.Action) (bool, runtime.Object, error) {
-                               deleteAction, ok := action.(k8stesting.DeleteActionImpl)
-                               if !ok {
-                                       del := k8stesting.DeleteActionImpl{}
+                       testPodRemoval := func(podName string) (bool, runtime.Object, error) {
+                               t.Helper()

-                                       return true, nil, fmt.Errorf("unexpected action, expected %T, got %T", del, action)
-                               }
-
-                               if _, ok := expectedPodsRemovedNames[deleteAction.Name]; !ok {
-                                       t.Fatalf("Unexpected pod %q removed", deleteAction.Name)
+                               if _, ok := expectedPodsRemovedNames[podName]; !ok {
+                                       t.Fatalf("Unexpected pod %q removed", podName)
                                }

                                expectedPodRemovedMutex.Lock()
@@ -807,39 +802,39 @@ func Test_Running_agent(t *testing.T) {

                                // After removal attempt of all pods which are expected to be removed, allow real removal by test code.
                                return expectedPodRemoved >= 0, nil, nil
+                       }
+
+                       fakeClient.PrependReactor("delete", "pods", func(action k8stesting.Action) (bool, runtime.Object, error) {
+                               deleteAction, ok := action.(k8stesting.DeleteActionImpl)
+                               if !ok {
+                                       del := k8stesting.DeleteActionImpl{}
+
+                                       return true, nil, fmt.Errorf("unexpected action, expected %T, got %T", del, action)
+                               }
+
+                               return testPodRemoval(deleteAction.Name)
                        })

-                       fakeClient.PrependReactor(
-                               "create",
-                               "pods/eviction",
-                               func(action k8stesting.Action) (handled bool, ret runtime.Object, err error) {
-                                       createAction, ok := action.(k8stesting.CreateActionImpl)
-                                       if !ok {
-                                               del := k8stesting.CreateActionImpl{}
+                       // To save some line length below and effectively keep indentation consistent.
+                       verb := "create"

-                                               return true, nil, fmt.Errorf("unexpected action, expected %T, got %T", del, action)
-                                       }
+                       fakeClient.PrependReactor(verb, "pods/eviction", func(action k8stesting.Action) (bool, runtime.Object, error) {
+                               createAction, ok := action.(k8stesting.CreateActionImpl)
+                               if !ok {
+                                       del := k8stesting.CreateActionImpl{}

-                                       if eviction, ok := createAction.Object.(*policyv1.Eviction); !ok {
-                                               if _, ok := expectedPodsRemovedNames[eviction.GetObjectMeta().GetName()]; !ok {
-                                                       t.Fatalf("Unexpected eviction for %q created", createAction.Name)
-                                               }
-                                       }
+                                       return true, nil, fmt.Errorf("unexpected action, expected %T, got %T", del, action)
+                               }

-                                       expectedPodRemovedMutex.Lock()
-                                       defer expectedPodRemovedMutex.Unlock()
-                                       expectedPodRemoved--
+                               eviction, ok := createAction.Object.(*policyv1.Eviction)
+                               if !ok {
+                                       expectedEviction := &policyv1.Eviction{}

-                                       defer func(i int) {
-                                               if i == 0 {
-                                                       allExpectedPodsScheduledForRemoval <- struct{}{}
-                                                       allExpectedPodsScheduledForRemoval <- struct{}{}
-                                               }
-                                       }(expectedPodRemoved)
+                                       return true, nil, fmt.Errorf("unexpected eviction type, expected %T, got %T", expectedEviction, eviction)
+                               }

-                                       // After removal attempt of all pods which are expected to be removed, allow real removal by test code.
-                                       return expectedPodRemoved >= 0, nil, nil
-                               })
+                               return testPodRemoval(eviction.Name)
+                       })

                        expectedGetPodCalls := 1
                        podGetRequest := make(chan struct{}, expectedGetPodCalls)
```

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> -			if err := getAgentRunningError(t, testConfig); !errors.Is(err, expectedError) {
Unrelated, but can you also fix this test name `getting_nodes_for_deletion_fails` -> `getting_pods_for_deletion_fails` please?

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent.go
> +			return fmt.Errorf("deleting/evicting pods: %w", err)
It seems this code is not correct. We only ignore timeout errors, however, tests states:
- Running agent logs error but continues operating when removing pod on node fails
- Running agent logs error but continues operating when getting pods while waiting for termination fails
- Running agent stops with error when agent receives termination signal while waiting for all pods to be terminated

Perhaps we should check here fore context cancelled error and only return an error if that occurs?

Then first 2 tests should actually be merged into one (as we no longer have associated code paths with getting the pod while waiting and deleting the pod, as drain helper covers both) let's say `draining_node_fails`, so we have:
- Running agent logs error but continues operating when draining node fails
- Running agent stops with error when agent receives termination signal while waiting for all pods to be terminated

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent.go
> -	// Mirror pod or daemonset anyway..
Perhaps we could keep this comment around where we construct drain helper and define filters?

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent.go
> -			// Continue anyways, the reboot should terminate it.
This comment we can also keep.

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent.go
> -	// kube-controller-manager.
This comment I'd also keep where we define the filter. Or we could make it a comment to the related test, which I think is the best place for it.

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +// lifted from https://github.com/kubernetes/kubectl/blob/master/pkg/drain/drain_test.go.
I wonder why linter did not complain about this :thinking: 
```suggestion
// Lifted from https://github.com/kubernetes/kubectl/blob/master/pkg/drain/drain_test.go.
```

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +	// Delete pods when evict is called
```suggestion
	// Delete pods when evict is called.
```

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +		// Avoid the lock
If we keep this comment, it should end with dot.
```suggestion
		// Avoid the lock.
```

2022-04-26 20:46 UTC, invidian commented on pkg/agent/agent_test.go
> +				// Errorf because we can't call Fatalf from another goroutine
Ditto dot.
```suggestion
				// Errorf because we can't call Fatalf from another goroutine.
```

2022-04-28 06:42 UTC, jakekeeys commented on pkg/agent/agent_test.go
> +			addEvictionSupport(t, fakeClient, "v1")
the tests are only validating that we create the resource right now so i don't think its worth adding more to saturate v1beta1. i've dropped it in line with the other comments.

2022-04-28 06:48 UTC, jakekeeys commented on pkg/agent/agent_test.go
> +			t.Errorf("unknown version %s", version)
removed, no longer relevant

2022-04-28 06:48 UTC, jakekeeys commented on pkg/agent/agent_test.go
> +			t.Errorf("unknown version %s", version)
done this

2022-04-28 07:33 UTC, jakekeeys commented on pkg/agent/agent_test.go
> +				return true, nil, nil
spot on, adding the comment

2022-05-03 08:52 UTC, invidian commented
To debug a failing test, I suggest using `go test -run ^Test_Running_agent/after_marking_node_as_unschedulable/without_exceeding_pod_deletion_grace_period/waits_for_removed_pods_to_terminate_before_rebooting$`, this way the printed logs are not cluttered by other agent instances. It's because of a flaw in klog...

2022-05-03 10:12 UTC, jakekeeys commented
> To debug a failing test, I suggest using `go test -run ^Test_Running_agent/after_marking_node_as_unschedulable/without_exceeding_pod_deletion_grace_period/waits_for_removed_pods_to_terminate_before_rebooting$`, this way the printed logs are not cluttered by other agent instances. It's because of a flaw in klog...

This test actually passes for me which is why i didn't pick up on it, are you able to replicate the fail?

2022-05-03 10:29 UTC, invidian commented
Hmm, I can't get it to fail either. This test is awfully long too. Don't worry about it, I'll investigate why it fails on the CI. I usually suspect CI to be just slower in terms of CPU wait time, which can cause some timeouts, which are hard to reproduce on local, usually more powerful/less busy machines.

2022-05-03 10:32 UTC, invidian commented
Maybe you can try adding some log statements around this code:
```
          expectedPodRemovedMutex.Lock()
          rebootTriggerred <- expectedPodRemoved < 0
          expectedPodRemovedMutex.Unlock()
```

Especially before and after lock is acquired. Perhaps there is some contention there blocking reboot event from being published.

2022-05-03 17:07 UTC, invidian commented
I can reliably reproduce locally by running `GOMAXPROCS=2 go test -mod vendor -count 10 -failfast -race ./pkg/agent`.

2022-05-03 18:45 UTC, invidian commented
So from my debugging, the cause seems to be the contention on Go routines, which makes `client.Delete()` call to pass, but it does not actually remove the pod from the storage of fake client, as it's still returned by `client.List()`.

The fix seems to be just disable the parallelization of this test, which gives it a bit more priority in the execution and makes it stable. So just `t.Parallel()` call needs to be removed from `Test_Running_agent/after_marking_node_as_unschedulable/without_exceeding_pod_deletion_grace_period/waits_for_removed_pods_to_terminate_before_rebooting` test.

I'll review again the whole thing.

2022-05-03 22:29 UTC, invidian requested changes
Just few more nits, overall looks very good to me. I really appreciate your effort @jakekeeys.

It seems just one comment regarding change of tests and error returned when deleting pods fails remains to be solved.

2022-05-03 22:29 UTC, invidian commented on pkg/agent/agent.go
> +	clientset               kubernetes.Interface
NIT: We could add this field perhaps after `nc`, so we have all K8s fields in one place and simpler type fields at the bottom. This also sorts dependencies more from more significant to less significant (except the `nodeName` at the moment of course).

2022-05-03 22:29 UTC, invidian commented on pkg/agent/agent.go
> +	if len(errs) != 0 {
While `!=` is correct, `>` is more common and hence idiomatic.
```suggestion
	if len(errs) > 0 {
```

2022-05-03 22:29 UTC, invidian commented on pkg/agent/agent_test.go
> +				if _, ok := expectedPodsRemovedNames[podName]; !ok {
```suggestion
				t.Helper()
				
				if _, ok := expectedPodsRemovedNames[podName]; !ok {
```

2022-05-03 22:29 UTC, invidian commented on pkg/agent/agent_test.go
> +				func(action k8stesting.Action) (handled bool, ret runtime.Object, err error) {
I think it will be more readable this way
```suggestion
			fakeClient.PrependReactor("create", "pods/eviction",
				func(action k8stesting.Action) (handled bool, ret runtime.Object, err error) {
```

2022-05-03 22:29 UTC, invidian commented on pkg/agent/agent_test.go
> +
Unnecessary newline I guess.

2022-05-03 22:29 UTC, invidian commented on pkg/agent/agent_test.go
> +func addEvictionSupport(t *testing.T, clientset *fake.Clientset) {
I like how simple this is now!

2022-05-04 09:22 UTC, jakekeeys commented on pkg/agent/agent_test.go
> +
i wasn't adding them, thought it was a go fmt thing

2022-05-04 09:23 UTC, jakekeeys commented on pkg/agent/agent_test.go
> +func addEvictionSupport(t *testing.T, clientset *fake.Clientset) {
:)

2022-05-04 09:27 UTC, jakekeeys commented
> Just few more nits, overall looks very good to me. I really appreciate your effort @jakekeeys.
> 
> It seems just one comment regarding change of tests and error returned when deleting pods fails remains to be solved.

no problem and thanks for all your input into the pull request, sorry its been a bit slow, still haven't quite wrapped my head around the test suite and i've been chipping away at this around other things.

I just want to quickly verify some scheduler behaviour around pod disruption policies which ill do this morning and report back. once that's out the way i think i'm happy with everything.

2022-05-04 09:53 UTC, invidian commented on pkg/agent/agent_test.go
> +
I'm not sure, but if linters does not complain, let's get rid of it

2022-05-04 10:08 UTC, invidian commented
>no problem and thanks for all your input into the pull request, sorry its been a bit slow, still haven't quite wrapped my head around the test suite and i've been chipping away at this around other things.

Don't worry about the slowness :)

And about the test suite, while I think test structure (names, grouping etc.) is OK, the content of the tests, setup code etc. is definitely not something to take as an example :smile: I'm not happy with it either and I have an idea how the whole thing can be simplified in the future.

Unfortunately, current complexity of tests is the result of writing tests after writing code, as original agent code had no tests at all. And as I plan to refactor this code, I wanted to write tests for it first to reduce a chance of regressions. The very lengthy setup code for final stages of the code (of agent processing) and complexity of observing the performed actions is IMO a result of a sub-optimal design. More on that in #134.

2022-05-04 10:35 UTC, jakekeeys commented
pdbs all look good. the drain helper internally retries the eviction as expected and the global timeout is honoured.

```flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.623056       1 main.go:81] /bin/update-agent running
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.623115       1 agent.go:185] Setting info labels
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.623185       1 agent.go:578] Skipping missing update.conf: open /etc/flatcar/update.conf: no such file or directory
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.686508       1 agent.go:191] Checking annotations
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.695799       1 agent.go:215] Setting annotations map[string]string{"flatcar-linux-update.v1.flatcar-linux.net/reboot-in-progress":"false", "flatcar-linux-update.v1.flatcar-linux.net/reboot-needed":"false"}
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.728626       1 agent.go:245] Skipping marking node as schedulable -- node was marked unschedulable by an external source
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.728669       1 agent.go:260] Waiting for ok-to-reboot from controller...
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.728768       1 agent.go:398] Beginning to watch update_engine status
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:31:37.729991       1 agent.go:342] Updating status
flatcar-linux-update-agent-f4wp6 update-agent W0504 09:45:51.883902       1 agent.go:268] Error waiting for an ok-to-reboot: <nil>
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:51.884017       1 agent.go:272] Checking if node is already unschedulable
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:51.893912       1 agent.go:290] Setting annotations map[string]string{"flatcar-linux-update.v1.flatcar-linux.net/agent-made-unschedulable":"true", "flatcar-linux-update.v1.flatcar-linux.net/reboot-in-progress":"true"}
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:51.937451       1 agent.go:297] Marking node as unschedulable
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:51.973767       1 agent.go:308] Getting pod list for deletion
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.111694       1 agent.go:315] Deleting/Evicting 19 pods
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116301       1 agent.go:628] evicting pod sys-ingress-priv/internal-ingress-controller-v2-56cbc4c5fc-8kgbp
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116333       1 agent.go:628] evicting pod sys-prom/thanos-query-658857686-wrmb7
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116348       1 agent.go:628] evicting pod sys-flatcar/nebraska-7c849df797-g2nsk
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116355       1 agent.go:628] evicting pod sys-minio/etcd-0
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116384       1 agent.go:628] evicting pod sys-mon/thanos-query-shared-56568c9c48-2nzlm
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116319       1 agent.go:628] evicting pod sys-vault/vault-pki-7695449b6b-6fjpm
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116627       1 agent.go:628] evicting pod sys-vault/terraform-applier-0
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116457       1 agent.go:628] evicting pod sys-minio/minio-nas-gw-7956b6f56-6wfbw
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116665       1 agent.go:628] evicting pod sys-prom/thanos-store-0
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116463       1 agent.go:628] evicting pod fluxcd-ns2/whoami-74958f8d-cwmlt
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116685       1 agent.go:628] evicting pod sys-vault/vault-0
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116492       1 agent.go:628] evicting pod billing-keda/keda-operator-b9b995954-s9nxl
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116720       1 agent.go:628] evicting pod fluxcd-test/source-controller-7c5f4ccbd-v67km
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116966       1 agent.go:628] evicting pod sys-flatcar/nebraska-postgres-0
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116976       1 agent.go:628] evicting pod sys-gatekeeper/gatekeeper-controller-manager-59fc966cc8-jw92m
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.116570       1 agent.go:628] evicting pod sys-metallb/controller-656d4b597b-srx95
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.117428       1 agent.go:628] evicting pod sys-semaphore/semaphore-service-mirror-7f654d59bf-thqqn
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.117466       1 agent.go:628] evicting pod sys-flatcar/test-deployment-c7985ffff-vrlr2
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:52.117710       1 agent.go:628] evicting pod sys-mon/alertmanager-589d75c947-hpv8c
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:53.317216       1 request.go:665] Waited for 1.199843775s due to client-side throttling, not priority and fairness, request: POST:https://10.7.0.1:443/api/v1/namespaces/sys-prom/pods/thanos-store-0/eviction
flatcar-linux-update-agent-f4wp6 update-agent E0504 09:45:53.735181       1 agent.go:628] error when evicting pods/"test-deployment-c7985ffff-vrlr2" -n "sys-flatcar" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:45:58.735746       1 agent.go:628] evicting pod sys-flatcar/test-deployment-c7985ffff-vrlr2
flatcar-linux-update-agent-f4wp6 update-agent E0504 09:45:58.755224       1 agent.go:628] error when evicting pods/"test-deployment-c7985ffff-vrlr2" -n "sys-flatcar" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:46:03.484288       1 request.go:665] Waited for 3.185345779s due to client-side throttling, not priority and fairness, request: GET:https://10.7.0.1:443/api/v1/namespaces/sys-vault/pods/terraform-applier-0
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:46:03.755624       1 agent.go:628] evicting pod sys-flatcar/test-deployment-c7985ffff-vrlr2
....
flatcar-linux-update-agent-f4wp6 update-agent E0504 09:55:48.729034       1 agent.go:628] error when evicting pods/"test-deployment-c7985ffff-vrlr2" -n "sys-flatcar" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:55:53.729400       1 agent.go:628] evicting pod sys-flatcar/test-deployment-c7985ffff-vrlr2
flatcar-linux-update-agent-f4wp6 update-agent W0504 09:55:53.729507       1 agent.go:321] timed out draining node, continuing...
flatcar-linux-update-agent-f4wp6 update-agent I0504 09:55:53.729559       1 agent.go:327] Node drained, rebooting
- flatcar-linux-update-agent-f4wp6 › update-agent```

2022-05-04 11:25 UTC, jakekeeys commented on pkg/agent/agent_test.go
> +
they did so I've reverted that commit

2022-05-05 16:31 UTC, invidian commented on pkg/agent/agent_test.go
> +
```diff
$ git diff pkg/agent/
diff --git a/pkg/agent/agent_test.go b/pkg/agent/agent_test.go
index 1a0442c2..80b16e37 100644
--- a/pkg/agent/agent_test.go
+++ b/pkg/agent/agent_test.go
@@ -849,7 +849,6 @@ func Test_Running_agent(t *testing.T) {
                        })

                        t.Run("waits_for_removed_pods_to_terminate_before_rebooting", func(t *testing.T) {
-
                                select {
                                case <-ctx.Done():
                                        t.Fatalf("Timed out waiting for all pods to be scheduled for removal")
@@ -1545,7 +1544,6 @@ func Test_Running_agent(t *testing.T) {
                                                Namespace:       "default",
                                                OwnerReferences: testPodControllerReference(),
                                        },
-
                                        Spec: corev1.PodSpec{
                                                NodeName: testNode().Name,
                                        },
```

The following patch does not trigger linter for me and looks like what I'd expect. I'll also update the linter to latest version on CI.

2022-05-11 07:30 UTC, jakekeeys commented on pkg/agent/agent.go
> +			return fmt.Errorf("deleting/evicting pods: %w", err)
sorry just to clarify there are two interactions with the drain helper that can fail
* getting pods for deletion
* deleting or evicting pods
you want both to log and continue under any condition except for a global timeout but return the error where the context has been cancelled and the timeout has been reached?
this might be tricky not delved this deep into the drain helper but we pass both the context and the timeout as a duration and thus far its been returning based on the duration rather than context cancelled

2022-05-11 13:39 UTC, invidian commented on pkg/agent/agent.go
> +			return fmt.Errorf("deleting/evicting pods: %w", err)
>getting pods for deletion

No, this is tested separately and has a separate behavior. I'm talking about previous behavior when we were getting pod updates as part of the drain process, which no longer exits, hence the tests can be merged/removed.

Failing call to `drainer.DeleteOrEvictPods` should always log and continue except the situation when the context is cancelled (this is treated as a shutdown signal).

Perhaps it would make sense to call `drainer.DeleteOrEvictPods` in the goroutine and make a select on `ctx.Done()` and `errCh` from `drainer.DeleteOrEvictPods` to make it simpler to graps and for better error handling. Then I think we could error from `drainer.DeleteOrEvictPods` and let agent caller handle returned error from context timeout.

2022-05-12 07:52 UTC, jakekeeys commented on pkg/agent/agent.go
> +			return fmt.Errorf("deleting/evicting pods: %w", err)
its does yeah, that's a good idea with the routine and select, ill get started on that this morn

2022-05-12 09:09 UTC, invidian commented on pkg/agent/agent.go
> +	drainErr := make(chan error)
Let's have a buffer here so we don't block the goroutine from exiting if we never have a chance to read from the channel.
```suggestion
	drainErr := make(chan error, 1)
```

2022-05-12 09:09 UTC, invidian commented on pkg/agent/agent.go
> +	}(drainErr, pods)
I guess just passing like this should work just fine?
```suggestion
	go func() {
		drainErr <- drainer.DeleteOrEvictPods(pods.Pods())
	}()
```

2022-05-12 09:15 UTC, jakekeeys commented
sorry about the semgrep stuff, can't run it locally again, not looked into why yet

2022-05-12 13:22 UTC, invidian requested changes
Thanks @jakekeeys for updating the tests. Things are looking good. Just last few nits and we can merge this.

2022-05-12 13:22 UTC, invidian commented on pkg/agent/agent_test.go
> +					createAction, ok := action.(k8stesting.CreateActionImpl) //nolint:varnamelen // false positive
```suggestion
					createAction, ok := action.(k8stesting.CreateActionImpl) //nolint:varnamelen // False positive.
```

2022-05-12 13:22 UTC, invidian commented on pkg/agent/agent_test.go
> +					t.Fatalf("expected reboot received context done: %v", err)
```suggestion
					t.Fatalf("Expected reboot, got agent running error: %v", err)
```

2022-05-12 13:23 UTC, invidian commented on pkg/agent/agent.go
> +			return fmt.Errorf("deleting/evicting pods: %w", err)
Looking good now. Marking as resolved.

2022-05-12 14:27 UTC, invidian approved these changes
LGMT, will merge when CI is done.

2022-05-12 14:28 UTC, merged