Compatibility with Kubernetes 1.24
flatcar-linux/flatcar-linux-update-operator pull request #157
Opened 2022-05-30 10:53 UTC by ateleshev

# Compatibility with Kubernetes 1.24

The **ConfigMapLock** resource is deprecated and was removed from the latest version of Kubernetes (1.24)

As you can see in the code, they recommend using ConfigMapsLeasesResourceLock instead
https://github.com/kubernetes/client-go/blob/v0.24.1/tools/leaderelection/resourcelock/interface.go#L194-L195

```
case configMapsResourceLock:
	return nil, fmt.Errorf("configmaps lock is removed, migrate to %s", ConfigMapsLeasesResourceLock)
```

2022-05-30 11:22 UTC, invidian requested changes
Hey @ateleshev, thanks for your contribution!

I got confused at first, as I have cluster running K8s v1.24 and FLUO works just fine there. I wasn't able to see any warnings in the logs either. Only then I realized that this is about the v0.24 client libraries compatibility. I created #158 then to update the libraries, perhaps there is more deprecated code we use.

I left some comments about the changes, please have a look.

2022-05-30 11:22 UTC, invidian commented on pkg/operator/operator.go
> +func (k *Kontroller) withLeaderElection(stop <-chan struct{}, errCh chan<- error) context.Context {
Can we commit `err` -> `errCh` rename separately please? It makes reading the diff more difficult.

2022-05-30 11:51 UTC, ateleshev commented on pkg/operator/operator.go
> +func (k *Kontroller) withLeaderElection(stop <-chan struct{}, errCh chan<- error) context.Context {
@invidian done, https://github.com/flatcar-linux/flatcar-linux-update-operator/pull/159/files

2022-05-30 12:57 UTC, ateleshev commented
@invidian please review again

2022-05-30 16:55 UTC, invidian requested changes
The tests are still missing, so I suggested in the comments how we can make this code testable and how we can test it. Test name should be something like: `Test_Creating_new_operator/fails_when/creating_resource_lock_fails`, to be added in the existing suite which tests the constructor.

2022-05-30 16:55 UTC, invidian commented on pkg/operator/operator.go
> +		return nil, fmt.Errorf("new resourcelock: %w", err)
```suggestion
		return nil, fmt.Errorf("creating new resource lock: %w", err)
```

2022-05-30 16:55 UTC, invidian commented on pkg/operator/operator.go
> +		return fmt.Errorf("leader election: %w", err)
```suggestion
		return fmt.Errorf("initializing leader election: %w", err)
```

2022-05-30 16:55 UTC, invidian commented on pkg/operator/operator.go
> +		resourcelock.ConfigMapsLeasesResourceLock,
I wonder how can we make this testable. Perhaps we can make lock type configurable via operator config (but no need to expose it via CLI) and then pass some bad value there.

2022-05-30 16:55 UTC, invidian commented on pkg/operator/operator.go
> +		resourcelock.ConfigMapsLeasesResourceLock,
Even better, how about we create a resource lock in constructor (`New()` functioN) and we pass it via the `Kontroller` struct field? I think it should be safe.

2022-05-31 08:34 UTC, invidian requested changes
Some nits remaining, otherwise looks good :+1:

2022-05-31 08:34 UTC, invidian commented on pkg/operator/operator.go
> +	ResourceLock         string
We don't pass a lock here, just it's type.
```suggestion
	LockType         string
```

2022-05-31 08:34 UTC, invidian commented on pkg/operator/operator.go
> +func (c Config) Check() error {
There is no need to have this function exported.

Also, let's put both this function and newResourceLock (this function was in the right place before) below `New()`, so it follows the abstraction levels hierarchy.

BTW, I like having this validations in separate function as they grow, good idea.

2022-05-31 08:39 UTC, invidian commented on pkg/operator/operator.go
> +	kclient := config.Client
Maybe there is not even a need for intermediate variable here?

2022-05-31 08:58 UTC, ateleshev commented
@invidian done

2022-05-31 12:17 UTC, merged